services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./churns:/app/churns
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - ENV=development
    depends_on:
      - redis
    networks:
      - churns_net

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - churns_net

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front_end:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=https://08ae-2001-d08-d1-c1b6-5918-a5e6-a9ca-1b08.ngrok-free.app
      - NEXT_PUBLIC_WS_URL=wss://08ae-2001-d08-d1-c1b6-5918-a5e6-a9ca-1b08.ngrok-free.app/
      - INTERNAL_API_URL=http://api:8000
    depends_on:
      - api
    networks:
      - churns_net

volumes:
  redis_data:

networks:
  churns_net:
    driver: bridge 