version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: development
    ports:
      - "8000:8000"
    volumes:
      - ./churns:/app/churns
      - ./data:/app/data
      - ./.env:/app/.env:ro
    environment:
      - PYTHONPATH=/app
      - ENV=development
    depends_on:
      - redis
    networks:
      - churns_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 512M

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - churns_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./front_end:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      # Use localhost for development - can be overridden via .env
      #- NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      #- NEXT_PUBLIC_WS_URL=${NEXT_PUBLIC_WS_URL:-ws://localhost:8000}
      - NEXT_PUBLIC_API_URL=https://1890fc44c2ef.ngrok-free.app
      - NEXT_PUBLIC_WS_URL=wss://1890fc44c2ef.ngrok-free.app 
      - INTERNAL_API_URL=http://api:8000
      # Disable Next.js editor integration to prevent errors
      - REACT_EDITOR=none
      - BROWSER=none
    depends_on:
      - api
    networks:
      - churns_net
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M

volumes:
  redis_data:
    driver: local

networks:
  churns_net:
    driver: bridge 